spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mylogdb
    username: mylog
    password: mylog1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secretKey: 12345678901234567890123456789012
  refreshKey: 12345678901234567890123456789012

file:
  dir: /Users/suyeon/Documents/공부/TECHIT/프로젝트 과제/0618 블로그 만들기/files/