spring:
  application:
    name: mylog
  profiles:
    active: dev
  servlet:
    multipart:
      maxFileSize: 6MB # 파일 하나의 최대 크기
      maxRequestSize: 12MB  # 한 번에 최대 업로드 가능 용량

server:
  servlet:
    session:
      tracking-modes: cookie

upload:
  path: /upload/