spring:
  application:
    name: mylog
  profiles:
    active: dev

server:
  servlet:
    session:
      tracking-modes: cookie

file:
  dir: /Users/suyeon/Documents/공부/TECHIT/프로젝트 과제/0618 블로그 만들기/files/